{% set name = "botorch" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/botorch/archive/v{{ version }}.tar.gz
  sha256: 51a912f45793dd0876b367aa925df61490308e90d396872b0b231e014465f26e


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch >=1.5
    - gpytorch >=1.1.1
    - scipy
test:
  imports:
    - botorch
    - botorch.acquisition
    - botorch.exceptions
    - botorch.models
    - botorch.optim
    - botorch.posteriors
    - botorch.sampling
    - botorch.test_functions
    - botorch.utils
    - botorch.fit
    - botorch.gen
    - botorch.settings

about:
  home: https://botorch.org
  license: MIT
  license_file: LICENSE
  summary: Bayesian Optimization in PyTorch
  doc_url: https://botorch.org/docs/introduction
  dev_url: https://github.com/pytorch/botorch

  description: |
    BoTorch is a library for Bayesian Optimization built on PyTorch.

extra:
  recipe-maintainers:
    - maclandrol
