{% set name = "botorch" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pytorch/botorch/archive/v{{ version }}.tar.gz
  sha256: ba8f68ec911070245d96ce10fb6b9d557cc5319037c7e4b57dd7f1549b3d097c


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytorch >=1.4
    - gpytorch >=1.0.0
    - scipy
test:
  imports:
    - botorch
    - botorch.acquisition
    - botorch.exceptions
    - botorch.models
    - botorch.optim
    - botorch.posteriors
    - botorch.sampling
    - botorch.test_functions
    - botorch.utils
    - botorch.fit
    - botorch.gen
    - botorch.settings

about:
  home: https://botorch.org
  license: MIT
  license_file: LICENSE
  summary: Bayesian Optimization in PyTorch
  doc_url: https://botorch.org/docs/introduction
  dev_url: https://github.com/pytorch/botorch

  description: |
    BoTorch is a library for Bayesian Optimization built on PyTorch.

extra:
  recipe-maintainers:
    - maclandrol
